# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

$script = <<-CSCRIPT 
cat<<-EOF >/etc/yum.repos.d/localvagrant.repo
[localVagrant]
name=CentOS-$releasever - local vagrant packages for $basearch
baseurl=file:///vagrant/repo/centos/7/x86_64/
enabled=1
gpgcheck=0
protect=1  
EOF
  rpm -import /vagrant/rpm-gpg/RPM-GPG-KEY-puppet
  yum -y install puppet-agent 
  /opt/puppetlabs/puppet/bin/gem install zabbixapi
CSCRIPT

  config.vm.define :central, primary: true  do |central| 
   central.vm.network "forwarded_port", guest: 80, host: 8080
   central.vm.network "forwarded_port", guest: 15672, host: 15672
   central.vm.provider :libvirt do |libvirt, override|
      libvirt.memory = 2048
      libvirt.cpus = 2
      libvirt.nested = true
    end
    central.vm.hostname = "central"
    central.vm.box = "centos/7"
    central.vm.provision :shell do |shell|
      shell.inline = $script
    end
    central.vm.provision "shell", inline: "/opt/puppetlabs/bin/puppet apply --modulepath=/vagrant/puppet/modules /vagrant/puppet/manifests/site.pp"
#    central.vm.provision :puppet do |puppet|  this provisioning method  is compatible  only with puppet < 4  && for some modules like puppet/zabbix puppet>=4 is required 
#      puppet.manifests_path = "puppet/manifests"
#      puppet.module_path = "puppet/modules"
#      puppet.hiera_config_path = "puppet/hiera.yaml"
#      puppet.manifest_file = "site.pp"
#    end
  end
  config.vm.define :worker do |worker| 
    worker.vm.hostname = "worker"
    worker.vm.box = "centos/7"
    worker.vm.provision :shell do |shell|
      shell.inline = $script
    end
    worker.vm.provision "shell", inline: "/opt/puppetlabs/bin/puppet apply --modulepath=/vagrant/puppet/modules /vagrant/puppet/manifests/site.pp"
  end

  (1..9).each do |i|
    config.vm.define "worker_#{i}",autostart: false do |node|
      node.vm.hostname = "worker-#{i}"
      node.vm.box = "centos/7"
      node.vm.provision :shell do |shell|
        shell.inline = $script
      end
      node.vm.provision "shell", inline: "/opt/puppetlabs/bin/puppet apply --modulepath=/vagrant/puppet/modules /vagrant/puppet/manifests/site.pp"
    end
  end

end
